language: node_js
env:
  matrix:
  - CI=true
  global:
    secure: PVWxNcBRCDT2i2oRGyMvBWfDOjPPorIxX+qMklVnladDx4U2pOVxFYTJoCPnscahpfIuzmhY+sRRtyeHrL97rUBOsOUDhiWb1/IkPMsp353crh1dTH6dHN0bcj6O6ASAnExsQoy85uwM3re5VBFGug/T3kMLLUu9VubNDMgFOTY=
sudo: false
node_js:
- '12'
install:
- npm install
script:
- npm test
- npm run build
- npm run chromatic
